"""add missing trip cover image column

Revision ID: 371d97ca9a17
Revises: 9d6955a3744a
Create Date: 2026-09-14 19:57:11.272212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371d97ca9a17'
down_revision: Union[str, Sequence[str], None] = '9d6955a3744a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'cover_image_url')
    # ### end Alembic commands ###
