"""add travel style to trip

Revision ID: ba08c026e820
Revises: cc813d1450d9
Create Date: 2026-09-13 23:58:15.239575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba08c026e820'
down_revision: Union[str, Sequence[str], None] = 'cc813d1450d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('travel_style', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'travel_style')
    # ### end Alembic commands ###
